--Tablas
DROP TABLE EGRESO;
DROP TABLE PRODUCTO_ORDEN;
DROP TABLE ORDEN_COMPRA;
DROP TABLE PROMOCION_PEDIDO;
DROP TABLE PLATO_PROMOCION;
DROP TABLE PROMOCION;
DROP TABLE PLATO_PEDIDO;
DROP TABLE CALIFICACION;
DROP TABLE PAGO_RESERVA;
DROP TABLE PAGO_PEDIDO;
DROP TABLE PEDIDO;
DROP TABLE RESERVA;
DROP TABLE MESA;
DROP TABLE CONTRATO;
DROP TABLE EMPLEADO;
DROP TABLE ROL;
DROP TABLE MENU_DIA;
DROP TABLE INVENTARIO;
DROP TABLE EVENTO;
DROP TABLE SUCURSAL;
DROP TABLE CLIENTE;
DROP TABLE PLATO_PRODUCTO;
DROP TABLE PLATO;
DROP TABLE PROVEEDOR_PRODUCTO;
DROP TABLE PRODUCTO;
DROP TABLE PROVEEDOR;
DROP TABLE RESTAURANTE;

--Funciones y procedimientos
DROP FUNCTION file_to_blob;
DROP FUNCTION CALCULAR_DISTANCIA;

--Triggers


--Objetos
DROP TYPE DIRECCION;
DROP TYPE DATOS_BASICOS;
DROP TYPE HORARIO;
DROP TYPE CALENDARIO;

--Otros
DROP DIRECTORY BLOBS;