--Tablas
DROP TABLE INVENTARIO;
DROP TABLE EVENTO;
DROP TABLE SUCURSAL;
DROP TABLE CLIENTE;
DROP TABLE PLATO_PRODUCTO;
DROP TABLE PLATO;
DROP TABLE PROVEEDOR_PRODUCTO;
DROP TABLE PRODUCTO;
DROP TABLE PROVEEDOR;
DROP TABLE RESTAURANTE;

--Funciones y procedimientos
DROP FUNCTION file_to_blob;
DROP FUNCTION CALCULAR_DISTANCIA;

--Triggers


--Objetos
DROP TYPE DIRECCION;
DROP TYPE DATOS_BASICOS;

--Otros
DROP DIRECTORY BLOBS;