--EMPLEADOS
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Walter.jpg'), '7-sep-1958', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(1234567), 'Walter', NULL, 'Blanco', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Jesse.jpg'), '10-sep-1984', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(4234568), 'José', 'Miguel', 'Rosas', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Saul.jpg'), '12-nov-1960', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(2234567), 'Saul', NULL, 'Bueno', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Jaisenber.jpg'), '7-sep-1958', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(1234568), 'Jaisenber', NULL, 'Blanco', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Skyler.jpg'), '8-nov-1970', 'F',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(6531272), 'Cielo', NULL, 'Blanco', 'Lambert'));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Marie.jpg'), '15-jun-1972', 'F',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(6831272), 'María', NULL, 'Navarro', 'Lambert'));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Hank.jpg'), '19-mar-1966', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(5673468), 'Henry', NULL, 'Navarro', 'Lambert'));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('WaltJr.jpg'), '8-jul-1993', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(12345762), 'Walter Jr', NULL, 'Blanco', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Gustavo.jpg'), '24-jan-1958', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(1235794), 'Gustavo', NULL, 'Cortés', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Lydia.jpg'), '27-may-1975', 'F',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(8726452), 'Lidia', NULL, 'Barrera', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Mike.jpg'), '31-jan-1942', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(1093020), 'Mario', NULL, 'Arboleda', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Nacho.jpg'), '9-dec-1971', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(8452152), 'Ignacio', NULL, 'Varga', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Lalo.jpg'), '12-aug-1960', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(8452152), 'Eduardo', NULL, 'Salamanca', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Kim.jpg'), '13-feb-1968', 'F',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(7260984), 'Kimberly', NULL, 'Wexler', NULL));
INSERT INTO EMPLEADO (ID, FOTO_CARNET, FECHA_NACIMIENTO, SEXO, DATOS)
VALUES (EMPLEADO_SEQ.nextval, FILE_TO_BLOB('Dwight.jpg'), '20-jan-1970', 'M',
        DATOS_BASICOS(DATOS_BASICOS.VALIDARCI(9230142), 'Dwight', NULL, 'Schrute', NULL));
