DECLARE
    cap NUMBER;
begin
    FOR I IN(SELECT *
             FROM PRODUCTO)
    LOOP

        SELECT MAX(CANTIDAD)*20
        INTO cap
        FROM PLATO_PRODUCTO PP, PRODUCTO PR, PLATO PL
        WHERE PP.id_producto=PR.ID AND PP.CODIGO_PLATO=PL.CODIGO AND PR.ID = I.ID;

        FOR J IN (SELECT ID FROM SUCURSAL)
        LOOP
            INSERT INTO INVENTARIO (ID_PRODUCTO,ID_SUCURSAL,FECHA_INVENTARIO,CAPACIDAD_MAXIMA,CANTIDAD) VALUES
            (I.ID,J.ID,CURRENT_DATE,cap,cap*0.2);
        END LOOP;
    END LOOP;
end;

SELECT * FROM INVENTARIO;
SELECT * FROM PRODUCTO;

DELETE FROM INVENTARIO;