-- INGREDIENTES PARA PIZZA
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Masa','Kg');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Tomate','Kg');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Queso mozarella','Kg');

-- INGREDIENTES PARA HAMBURGUESA
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Pan','U');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Carne molida','Kg');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Queso americano','Kg');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Lechuga','Kg');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Salsa','L');

-- INGREDIENTES PASTA
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Spaghetti','Kg');

-- INGREDIENTES PASTA
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Jamon','Kg');

-- BEBIDAS
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Agua minalba 600ml','U');

INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Coca-Cola Lata 355ml','U');

INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Cerveza Polar botella 222ml','U');

INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Margarita','U');

INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Fresa','Kg');

-- POSTRES
-- TRES LECHES
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Leche condensada','L');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Leche entera','L');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Leche evaporada','L');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Huevo','U');
-- Helado de mantecado
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Helado mantecado','L');
-- Marquesa de chocolate
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Mantequilla','Kg');
INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Chocolate','Kg');

INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Banana','Kg');

INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Pasta lasaña','Kg');

INSERT INTO PRODUCTO (ID, DESCRIPCION, UNIDAD_MEDIDA)
VALUES (PRODUCTO_SEQ.nextval,'Harina','Kg');

-- PLATO_PRODUCTO

-- PIZZA
--MASA
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (1,1,0.25);
-- TOMATE
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (1,2,0.25);
-- QUESO MOZARELLA
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (1,3,0.25);

-- HAMBURGUESA
-- Pan
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (2,4,1);
-- TOMATE
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (2,2,0.08);
-- LECHUGA
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (2,7,0.08);
-- QUESO AMERICANO
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (2,6,0.1);
-- SALSA
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (2,8,0.05);
-- CARNE MOLIDA
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (2,5,0.25);

-- PASTA
-- SPAGHETTI
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (3,9,0.15);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (3,5,0.2);

-- PASTICHO
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (4,24,0.2);
-- TOMATE
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (4,2,0.2);
-- LECHE
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (4,17,0.1);
-- CARNE
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (4,5,0.15);


-- ENSALADA
-- TOMATE
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (5,2,0.3);
-- LECHUGA
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (5,7,0.3);
-- QUESO MOZARELLA
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (5,3,0.3);

-- BEBIDAS
-- Agua
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (6,11,1);
-- Coca-Cola
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (7,12,1);
-- Cerveza Polar
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (8,13,1);
-- Margarita
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (9,14,1);
-- Jugo de fresa
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (10,15,0.1);


-- POSTRES
-- TRES LECHES
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (11,17,1);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (11,18,1);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (11,19,2);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (11,16,0.25);

-- Helado de mantecado
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (12,20,0.25);

-- MARQUESA DE CHOCOLATE
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (13,18,0.01);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (13,19,1);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (13,21,0.25);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (13,22,0.2);

-- BROWNIE
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (14,18,0.01);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (14,19,1);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (14,21,0.25);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (14,22,0.2);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (14,25,0.2);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (14,20,0.25);

-- BANANA SPLIT
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (15,23,0.2);
INSERT INTO PLATO_PRODUCTO (CODIGO_PLATO, ID_PRODUCTO, CANTIDAD)
VALUES (15,20,0.25);
